### ISSUE TITLE
Issue in starting the server

### ISSUE THREAD

**Issue by kumarpradeephk** [gobuffalo/docs#518]
I created a sample API only application using the command `buffalo new sample-app --api --db-type mysql` and it successfully created the project structure and able to start the server. but when I just change the database.yml config. it is throwing the error while starting the server.

```
buffalo: 2019/10/20 21:03:07 === exit status 1
2019/10/20 21:03:07 couldn't unmarshal config to yaml: yaml: unmarshal errors:
  line 34: cannot unmarshal !!map into string
  line 35: cannot unmarshal !!map into string
  line 36: cannot unmarshal !!map into string
  line 37: cannot unmarshal !!map into string
 ===
```

**Comment by kteb** [comment]
Could you  give us a sample of your database.yml (without the real password obviously)

**Comment by sirkay777** [comment]
Same error here. Open `database.yml` with vscode and save, the `prettier` plugin will reformat yaml file, and `buffalo dev` will report this error. Here is a diff showing what lines `prettier` have changed.

![Snip20200315_30](https://user-images.githubusercontent.com/2386695/76696830-b12a7c80-66ca-11ea-8bb7-83184eb3cf55.png)
![Snip20200315_29](https://user-images.githubusercontent.com/2386695/76696833-b5ef3080-66ca-11ea-8061-00a4fa83f67a.png)

**Comment by sirkay777** [comment]
It turns out that I have both `prettier` and `yaml` plugin installed on my vscode. They both have `Bracket Spacing` option checked by default.

![Snip20200315_35](https://user-images.githubusercontent.com/2386695/76697093-8db50100-66cd-11ea-90f4-73a4f592a8fb.png)
![Snip20200315_34](https://user-images.githubusercontent.com/2386695/76697094-8f7ec480-66cd-11ea-8c71-d69ab696e232.png)
